List<String> issueImages = [
  'assets/issues/Watersupply.png', // Updated filename
  'assets/issues/highway.png',
  'assets/issues/healthcare.png',
  'assets/issues/eco-friendly.png',
  'assets/issues/tower.png',
  'assets/issues/agriculture.png',
  'assets/issues/liquid-soap.png',
  'assets/issues/bus.png',
  'assets/issues/protection.png',
  'assets/issues/housing.png',  
  'assets/issues/corruption.png',
  'assets/issues/law.png',
  'assets/issues/human-rights.png',
  'assets/issues/animal-rights.png',
  'assets/issues/others.png',
];

List<String> issueLabels = [
  'Water Supply',
  'Road Line',
  'Health',
  'Environment',
  'Electricity',
  'Education',
  'Infrastructure',
  'Agriculture',
  'Sanitation',
  'Public Transport',
  'Safety',
  'Housing',
  'Corruption',
  'Law and Order',
  'Human Rights',
  'Animal Rights',  
  'Others',
];
