# Generated by Django 5.1.4 on 2024-12-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvote_set', to='issue.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_downvotes', to='authentication.user')),
            ],
            options={
                'unique_together': {('issue', 'user')},
            },
        ),
    ]
